#include <nui/core.hpp>
#include <nui/window.hpp>

// This file is generated by nui.
#include <index.hpp>

#include <filesystem>

int main(int, char** argv)
{
    auto const selfPath = std::filesystem::path{argv[0]}.parent_path();

    using namespace Nui;

    Window window{{
        .title = "Nui",
        .debug = true,
    }};
    window.setSize(1600, 1000, WebViewHint::WEBVIEW_HINT_NONE);
    window.centerOnPrimaryDisplay();
    window.setVirtualHostNameToFolderMapping("modules", selfPath / "modules", HostResourceAccessKind::Allow);
    window.setHtml(index());
    window.run();
}